### ISSUE TITLE
user password stored on disk

### ISSUE THREAD

**Issue by soellman** [rimusz/coreos-xhyve-ui#2]
I'd love to run this but storing my user password on disk unencrypted isn't something I'm willing to do.

Can you make it so it just asks for my password when needed? Or provide instructions on what to add to sudoers or something?

**Comment by rimusz** [comment]
@soellman password is encrypted by base64 so it is not the plain text

**Comment by soellman** [comment]
base64 isn't encryption.. anyone can decode it without any credentials.

**Comment by rimusz** [comment]
@soellman this is a temporal solution till xhyve works without sudo, but password is saved in your user home folder, I do not see that a big problem if you do not give psychical access to your Mac and user to somebody else.

**Comment by soellman** [comment]
To each his own :)

**Comment by rimusz** [comment]
@soellman so storing the password that way should not be big problem :)

**Comment by xez** [comment]
Perhaps as a workaround one could use _setuid_ at install time:

```
sudo chown root build/xhyve
sudo chmod +s build/xhyve
```

So xhyve will not require an explicit `sudo` to run with networking. Even better would be to add a patch to xhyve to drop the root privileges as soon as it has instantiated the network connections.

**Comment by rimusz** [comment]
@xez thanks for the tip, will check it out

**Comment by kryton** [comment]
another option is to tell us which commands you need sudo for, and we could then allow them in the /etc/sudoers file as (nopasswd).

**Comment by rimusz** [comment]
@kryton I already tried shudders option for xhyve, it did not work all the time, this why I went storing password in the file and passing it to sudo command

**Comment by rimusz** [comment]
as I have not find good work around solution with our storing password to the file, I will close this one for now
