### ISSUE TITLE
can't create VM as GPG isn't executing

### ISSUE THREAD

**Issue by kryton** [rimusz/coreos-xhyve-ui#3]
It seems to be stuck in getting a IP-address.

before that it complains about gpg missing a library

$ ./gpg 
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib

**Comment by rimusz** [comment]
@kryton I include homebrew gpg binary which I see needs that library file, need to look for other options, if not will recommend user to install it by himself.

**Comment by rimusz** [comment]
took gpg binary away, it now will successfully download ISO files without it
